public class MathematicalClass {
        public Integer addition(Integer x, integer y) {
        integer sum = x + y;
        return sum;
    }
    public Integer subtraction(Integer x, integer y) {
        integer difference = x - y;
        return difference;
    }
    public Integer multiplication(Integer x, integer y) {
        integer product = x * y;
        return product;
    }
    public Integer division(Integer x, integer y) {
        integer quotient = x / y;
        return quotient;
    }
}