rankPrizeSwitch rh = new rankPrizeSwitch();
string won = rh.rankPrize(1);
system.debug('for rank 1 prize is ' + won);

string won2 = rh.rankPrize(2);
system.debug('for rank 2 prize is ' + won2);

string won3 = rh.rankPrize(3);
system.debug('for rank 3 prize is ' + won3);

string won4 = rh.rankPrize(8);
system.debug('for rank 8 prize is ' + won4);

string won5 = rh.rankPrize(40);
system.debug('for rank 40 prize is ' + won5);